project_id = "jzwiotevtwxbmeibtqkb"

[functions.create-admin-user]
verify_jwt = false

[functions.generate-phone-numbers]
verify_jwt = false

[functions.seed-phone-numbers]
verify_jwt = false

[functions.send-webhook]
verify_jwt = false